services:
  web:
    build: ./src
    ports: 
      - 80:80
  mariadb:
    image: mariadb:10.5
    environment:
      - MYSQL_DATABASE=appname
      - MYSQL_USER=appname
      - MYSQL_PASSWORD=${MARIADB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
    volumes:
      - mariadb-volume:/etc/data
    profiles:
      - db
volumes:
  mariadb-volume: